// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {api} from '../models';
import {request} from '../models';

export function GoodsAll():Promise<api.RespData[[]goods-system/internal/application/vo>;

export function GoodsDelete(arg1:string):Promise<api.RespData[go/types>;

export function GoodsEdit(arg1:request.GoodsEditRequest):Promise<api.RespData[go/types>;

export function GoodsGetById(arg1:string):Promise<api.RespData[goods-system/internal/application/vo>;

export function GoodsPage(arg1:request.GoodsPageRequest):Promise<api.RespData[goods-system/internal/infrastructure/common/api>;

export function GoodsSave(arg1:request.GoodsSaveRequest):Promise<api.RespData[go/types>;

export function GoodsTypeDeleteByName(arg1:request.GoodsTypeDeleteRequest):Promise<api.RespData[go/types>;

export function GoodsTypeSave(arg1:request.GoodsTypeSaveRequest):Promise<api.RespData[go/types>;

export function GoodsTypeSelectAll():Promise<api.RespData[[]goods-system/internal/application/vo>;

export function GoodsTypeUpdate(arg1:request.GoodsTypeEditRequest):Promise<api.RespData[go/types>;

export function ImportBackup(arg1:string):Promise<api.RespData[interface {}]>;

export function MemberAll():Promise<api.RespData[[]goods-system/internal/application/vo>;

export function MemberDeleteById(arg1:string):Promise<api.RespData[go/types>;

export function MemberGetById(arg1:string):Promise<api.RespData[goods-system/internal/application/vo>;

export function MemberGetByPhone(arg1:string):Promise<api.RespData[goods-system/internal/application/vo>;

export function MemberLevelDeleteById(arg1:string):Promise<api.RespData[go/types>;

export function MemberLevelSave(arg1:request.MemberLevelSaveRequest):Promise<api.RespData[go/types>;

export function MemberLevelSelectAll():Promise<api.RespData[[]goods-system/internal/application/vo>;

export function MemberLevelUpdate(arg1:request.MemberLevelUpdateRequest):Promise<api.RespData[go/types>;

export function MemberPage(arg1:request.MemberPageRequest):Promise<api.RespData[goods-system/internal/infrastructure/common/api>;

export function MemberSave(arg1:request.MemberSaveRequest):Promise<api.RespData[go/types>;

export function MemberUpdate(arg1:request.MemberUpdateRequest):Promise<api.RespData[go/types>;

export function Order(arg1:request.OrderRequest):Promise<api.RespData[go/types>;

export function OrderPage(arg1:request.OrderPageRequest):Promise<api.RespData[goods-system/internal/infrastructure/common/api>;

export function OrderRecords(arg1:request.OrderRecordRequest):Promise<api.RespData[[]goods-system/internal/application/vo>;

export function OrderStatistics(arg1:request.OrderRecordRequest):Promise<api.RespData[goods-system/internal/application/vo>;

export function SystemBackup(arg1:string):Promise<api.RespData[go/types>;

export function SystemDesktopPath():Promise<api.RespData[goods-system/internal/application/vo>;
