// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GoodsAll() {
  return window['go']['main']['App']['GoodsAll']();
}

export function GoodsDelete(arg1) {
  return window['go']['main']['App']['GoodsDelete'](arg1);
}

export function GoodsEdit(arg1) {
  return window['go']['main']['App']['GoodsEdit'](arg1);
}

export function GoodsGetById(arg1) {
  return window['go']['main']['App']['GoodsGetById'](arg1);
}

export function GoodsPage(arg1) {
  return window['go']['main']['App']['GoodsPage'](arg1);
}

export function GoodsSave(arg1) {
  return window['go']['main']['App']['GoodsSave'](arg1);
}

export function GoodsTypeDeleteByName(arg1) {
  return window['go']['main']['App']['GoodsTypeDeleteByName'](arg1);
}

export function GoodsTypeSave(arg1) {
  return window['go']['main']['App']['GoodsTypeSave'](arg1);
}

export function GoodsTypeSelectAll() {
  return window['go']['main']['App']['GoodsTypeSelectAll']();
}

export function GoodsTypeUpdate(arg1) {
  return window['go']['main']['App']['GoodsTypeUpdate'](arg1);
}

export function ImportBackup(arg1) {
  return window['go']['main']['App']['ImportBackup'](arg1);
}

export function MemberAll() {
  return window['go']['main']['App']['MemberAll']();
}

export function MemberDeleteById(arg1) {
  return window['go']['main']['App']['MemberDeleteById'](arg1);
}

export function MemberGetById(arg1) {
  return window['go']['main']['App']['MemberGetById'](arg1);
}

export function MemberGetByPhone(arg1) {
  return window['go']['main']['App']['MemberGetByPhone'](arg1);
}

export function MemberLevelDeleteById(arg1) {
  return window['go']['main']['App']['MemberLevelDeleteById'](arg1);
}

export function MemberLevelSave(arg1) {
  return window['go']['main']['App']['MemberLevelSave'](arg1);
}

export function MemberLevelSelectAll() {
  return window['go']['main']['App']['MemberLevelSelectAll']();
}

export function MemberLevelUpdate(arg1) {
  return window['go']['main']['App']['MemberLevelUpdate'](arg1);
}

export function MemberPage(arg1) {
  return window['go']['main']['App']['MemberPage'](arg1);
}

export function MemberSave(arg1) {
  return window['go']['main']['App']['MemberSave'](arg1);
}

export function MemberUpdate(arg1) {
  return window['go']['main']['App']['MemberUpdate'](arg1);
}

export function Order(arg1) {
  return window['go']['main']['App']['Order'](arg1);
}

export function OrderPage(arg1) {
  return window['go']['main']['App']['OrderPage'](arg1);
}

export function OrderRecords(arg1) {
  return window['go']['main']['App']['OrderRecords'](arg1);
}

export function OrderStatistics(arg1) {
  return window['go']['main']['App']['OrderStatistics'](arg1);
}

export function SystemBackup(arg1) {
  return window['go']['main']['App']['SystemBackup'](arg1);
}

export function SystemDesktopPath() {
  return window['go']['main']['App']['SystemDesktopPath']();
}
